# The following variables are loaded from the .env file
#   BLUE_BLUE_GITHUB_REPO
#   BLUE_ROS_DISTRO
#
# These targets are exclusively for building respective images.  See compose/ for running images.

services:
  ci:
    image: ghcr.io/${BLUE_GITHUB_REPO:?Github repo not set}:${BLUE_ROS_DISTRO:?BLUE_ROS_DISTRO not set}-ci
    build: &default_build
      dockerfile: .docker/Dockerfile
      target: ci
      context: ../
      args:
        - ROS_DISTRO=${BLUE_ROS_DISTRO}
      cache_from:
        - ghcr.io/${BLUE_GITHUB_REPO}:${BLUE_ROS_DISTRO}-ci-cache
        - ghcr.io/${BLUE_GITHUB_REPO}:${BLUE_ROS_DISTRO}-robot-cache
        - ghcr.io/${BLUE_GITHUB_REPO}:${BLUE_ROS_DISTRO}-desktop-cache
        - ghcr.io/${BLUE_GITHUB_REPO}:${BLUE_ROS_DISTRO}-desktop-nvidia-cache
      cache_to:
        - ghcr.io/${BLUE_GITHUB_REPO}:${BLUE_ROS_DISTRO}-ci-cache
      x-bake:
        platforms:
          - linux/amd64
  #          - linux/arm64

  robot:
    build:
      <<: *default_build
      target: robot
      cache_to:
        - ghcr.io/${BLUE_GITHUB_REPO}:${BLUE_ROS_DISTRO}-robot-cache
    image: ghcr.io/${BLUE_GITHUB_REPO}:${BLUE_ROS_DISTRO}-robot

  desktop:
    build:
      <<: *default_build
      target: desktop
      cache_to:
        - ghcr.io/${BLUE_GITHUB_REPO}:${BLUE_ROS_DISTRO}-desktop-cache
    image: ghcr.io/${BLUE_GITHUB_REPO}:${BLUE_ROS_DISTRO}-desktop

  desktop-nvidia:
    build:
      <<: *default_build
      target: desktop-nvidia
      cache_to:
        - ghcr.io/${BLUE_GITHUB_REPO}:${BLUE_ROS_DISTRO}-desktop-nvidia-cache
    image: ghcr.io/${BLUE_GITHUB_REPO}:${BLUE_ROS_DISTRO}-desktop-nvidia
